### ISSUE TITLE
 pre.aut is not supported 

### ISSUE THREAD

**Issue by naerabati** [alan23273850/AutoQ#10]
The error `FromFileToAutomata: The filename extension is not supported.` comes up when trying to run the example verifications, and the readme is not updated for running with pre.spec

**Comment by alan23273850** [comment]
Thank you for pointing out this mistake! As mentioned in #7, the supported filename extension has been changed from *.aut to *.spec. I will update the README in a few days. Sorry for the inconvenience.

**Comment by alan23273850** [comment]
I've just updated the README.md in the `main` branch. Please re-open this issue if there is still any problem. Thanks!
