### ISSUE TITLE
Error : make release and debug

### ISSUE THREAD

**Issue by jricc** [alan23273850/AutoQ#11]
Hello, 

I've installed the dependencies, but I still get an error during installation.
With `make release`, I get this error: 
```
/home/debian/AutoQ/src/../include/z3/z3++.h:590:9: warning: ‘z3::ast_vector_tpl<z3::func_decl>::m_vector’ should be initialized in the member initialization list [-Weffc++]
make[3]: Leaving directory '/home/debian/AutoQ/build'
make[2]: *** [CMakeFiles/Makefile2:900: src/CMakeFiles/autoq.dir/all] Error 2
make[2]: Leaving directory '/home/debian/AutoQ/build'
make[1]: *** [Makefile:101: all] Error 2
make[1]: Leaving directory '/home/debian/AutoQ/build'
make: *** [Makefile:15: release] Error 2
```
And with `make debug`, I have this one:
```
/home/debian/AutoQ/src/timbuk_parser-nobison.cc:928:21: error: cannot convert ‘boost::enable_if_c<true, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<> > >::type’ {aka ‘boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<> >’} to ‘int’ in initialization
make[3]: *** [src/CMakeFiles/autoq.dir/build.make:76: src/CMakeFiles/autoq.dir/timbuk_parser-nobison.cc.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/home/debian/AutoQ/build'
make[2]: *** [CMakeFiles/Makefile2:900: src/CMakeFiles/autoq.dir/all] Error 2
make[2]: Leaving directory '/home/debian/AutoQ/build'
make[1]: *** [Makefile:101: all] Error 2
make[1]: Leaving directory '/home/debian/AutoQ/build'
make: *** [Makefile:12: debug] Error 2
```

Can you help me?

Thanks in advance.

**Comment by alan23273850** [comment]
Hello, I will try to fix it on Friday afternoon, Taiwan time.

Could you please show _all_ error messages for both cases? Your `make release` only includes a warning message without other error messages. Thank you.

**Comment by jricc** [comment]
Hello, of course, sorry. 
For `release` : 
'''
/home/debian/AutoQ/src/timbuk_parser-nobison.cc:928:21: error: cannot convert ‘boost::enable_if_c<true, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<> > >::type’ {aka ‘boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<> >’} to ‘int’ in initialization
  928 |                 int Q = aut.qubitNum + t2.first.symbol().qubit(); // we need to shift the qubit number
      |                     ^
/home/debian/AutoQ/src/timbuk_parser-nobison.cc: In instantiation of ‘static AUTOQ::Automata<Symbol> AUTOQ::Parsing::TimbukParser<Symbol>::from_line_to_automaton(std::string, const std::map<std::__cxx11::basic_string<char>, AUTOQ::Complex::FiveTuple>&) [with Symbol = AUTOQ::Symbol::Symbolic; std::string = std::__cxx11::basic_string<char>]’:
/home/debian/AutoQ/src/timbuk_parser-nobison.cc:1050:33:   required from here

/home/debian/AutoQ/src/timbuk_parser-nobison.cc:928:21: error: cannot convert ‘boost::enable_if_c<true, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<> > >::type’ {aka ‘boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<> >’} to ‘int’ in initialization
/home/debian/AutoQ/src/timbuk_parser-nobison.cc: In instantiation of ‘static AUTOQ::Automata<Symbol> AUTOQ::Parsing::TimbukParser<Symbol>::from_line_to_automaton(std::string, const std::map<std::__cxx11::basic_string<char>, AUTOQ::Complex::FiveTuple>&) [with Symbol = AUTOQ::Symbol::Predicate; std::string = std::__cxx11::basic_string<char>]’:
/home/debian/AutoQ/src/timbuk_parser-nobison.cc:1051:33:   required from here
/home/debian/AutoQ/src/timbuk_parser-nobison.cc:928:21: error: cannot convert ‘boost::enable_if_c<true, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<> > >::type’ {aka ‘boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<> >’} to ‘int’ in initialization
make[3]: *** [src/CMakeFiles/autoq.dir/build.make:76: src/CMakeFiles/autoq.dir/timbuk_parser-nobison.cc.o] Error 1
make[3]: *** Waiting for unfinished jobs....
```
For `debug` : 
```
/home/debian/AutoQ/src/timbuk_parser-nobison.cc:928:21: error: cannot convert ‘boost::enable_if_c<true, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<> > >::type’ {aka ‘boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<> >’} to ‘int’ in initialization
  928 |                 int Q = aut.qubitNum + t2.first.symbol().qubit(); // we need to shift the qubit number
      |                     ^
/home/debian/AutoQ/src/timbuk_parser-nobison.cc: In instantiation of ‘static AUTOQ::Automata<Symbol> AUTOQ::Parsing::TimbukParser<Symbol>::from_line_to_automaton(std::string, const std::map<std::__cxx11::basic_string<char>, AUTOQ::Complex::FiveTuple>&) [with Symbol = AUTOQ::Symbol::Symbolic; std::string = std::__cxx11::basic_string<char>]’:
/home/debian/AutoQ/src/timbuk_parser-nobison.cc:1050:33:   required from here
/home/debian/AutoQ/src/timbuk_parser-nobison.cc:928:21: error: cannot convert ‘boost::enable_if_c<true, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<> > >::type’ {aka ‘boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<> >’} to ‘int’ in initialization
/home/debian/AutoQ/src/timbuk_parser-nobison.cc: In instantiation of ‘static AUTOQ::Automata<Symbol> AUTOQ::Parsing::TimbukParser<Symbol>::from_line_to_automaton(std::string, const std::map<std::__cxx11::basic_string<char>, AUTOQ::Complex::FiveTuple>&) [with Symbol = AUTOQ::Symbol::Predicate; std::string = std::__cxx11::basic_string<char>]’:
/home/debian/AutoQ/src/timbuk_parser-nobison.cc:1051:33:   required from here
/home/debian/AutoQ/src/timbuk_parser-nobison.cc:928:21: error: cannot convert ‘boost::enable_if_c<true, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<> > >::type’ {aka ‘boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<> >’} to ‘int’ in initialization
In file included from /home/debian/AutoQ/src/../include/autoq/symbol/symbolic.hh:5,
                 from /home/debian/AutoQ/src/../include/autoq/aut_description.hh:19,
                 from /home/debian/AutoQ/src/util/execute.cc:1:
```
Thank you.

**Comment by alan23273850** [comment]
Hello, please replace the line `/home/debian/AutoQ/src/timbuk_parser-nobison.cc:928:21` with
`int Q = static_cast<int>(aut.qubitNum + t2.first.symbol().qubit()); // we need to shift the qubit number` or apply [this patch](https://github.com/alan23273850/AutoQ/commit/44ea3c0664034299f6a8712504ce2b1760b8c0ae).

Besides, I've made a lot of code refactors in the branch `CAV24`. Please take a look and use it if possible. Thanks!
(I will make `CAV24` the main branch if it is stable in the future.)
Note that the current difference between `CAV24` and `main` is that `CAV24` does not support predicate automata, so if you have the need you may want to switch to the `main` branch.

**Comment by jricc** [comment]
Hello, thank you very much for your reply.
I installed the patch and used the CAV24 branch (I also tried with the main branch), but I still get an error. I'm attaching 2 log files, one for `release`, one for `debug`.
Thanks again for your help.
[log_release.txt](https://github.com/alan23273850/AutoQ/files/14801483/log_release.txt)
[log_debug.txt](https://github.com/alan23273850/AutoQ/files/14801484/log_debug.txt)

**Comment by alan23273850** [comment]
Could you please switch to the compiler `g++` (instead of `c++`) first? I am not sure if you run AutoQ on Mac or not. If yes, there may be some problems which are expected. To my knowledge, it is not trivial to use `g++` on Mac?

I will try to fix it later. Thanks for your build logs.

**Comment by jricc** [comment]
Thank you very much for your reply.
I run AutoQ on Debian, not on Mac.
I tried with g++ (`g++ (Debian 12.2.0-14) 12.2.0`)
Thanks again for your help.
[log_release.txt](https://github.com/alan23273850/AutoQ/files/14802233/log_release.txt)

**Comment by alan23273850** [comment]
Now I compiled the project on Debian 12.4 from [https://www.osboxes.org/debian/#debian-12-4-0-vmware](https://www.osboxes.org/debian/#debian-12-4-0-vmware), and the error messages are the same as yours.

I will try to fix it on Saturday evening, Taiwan time.

**Comment by alan23273850** [comment]
@jricc I've updated the fix on this branch https://github.com/alan23273850/AutoQ/commit/aec588918324efd594e97e967b49fb6f2b9fe776. Please take a look. At least this version can be compiled successfully on my Debian VirtualBox. Feel free to contact me if this version still contains some problems. Thank you!
