### ISSUE TITLE
.aut missing ?

### ISSUE THREAD

**Issue by jricc** [alan23273850/AutoQ#7]
Hello,
I'm trying to use AutoQ, and I'm having a problem. Could you help me?
When I run this command:
`./build/cli/autoq benchmarks/BernsteinVazirani/02/pre.aut benchmarks/BernsteinVazirani/02/circuit.qasm`
I get this error:
```
Error: Unable to open file.
[ERROR] Unable to open the benchmarks/BernsteinVazirani/02/pre.aut file.
```
In addition, on Git I have:
![image](https://github.com/alan23273850/AutoQ/assets/84151847/60795181-3ffe-47b9-9963-93bd75b59ea2)

**Comment by alan23273850** [comment]
Hello, due to some reasons, we've decided to change the extension of pre and post from *.aut to *.spec afterwards.

Simply run `./build/cli/autoq benchmarks/BernsteinVazirani/02/pre.spec benchmarks/BernsteinVazirani/02/circuit.qasm`.
Sorry for the inconvenience.

**Comment by jricc** [comment]
Thank you.
